"""add user_id to conversations

Revision ID: b05d08fb5171
Revises: 40ea924b41d1
Create Date: 2026-10-04 06:15:17.009162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b05d08fb5171'
down_revision: Union[str, Sequence[str], None] = '40ea924b41d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate cannot know about existing rows, and a NOT NULL column
    # cannot be added to a table that already has any. These are throwaway
    # local conversations with no owner, so they are dropped.
    #
    # In production this would be three deploys instead: add the column
    # nullable, backfill it, then set NOT NULL -- because during a rolling
    # deploy the old code is still inserting rows that know nothing about
    # the new column.
    op.execute("DELETE FROM conversations")

    op.add_column('conversations', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_column('conversations', 'user_id')
    # ### end Alembic commands ###
